/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	
	public int add(int a,int b) {
		
      return a+b;
    }
	
	public int subs(int a,int b) {
		
	      return a-b;
	    }
}
